/**
 * Convert a CDS report object to a well-formatted Markdown document.
 */
export function reportToMarkdown(report: any): string {
  const lines: string[] = [];

  lines.push("# Clinical Decision Support Report");
  lines.push("");
  lines.push("*Generated by CDS Agent - MedGemma (HAI-DEF)*");
  lines.push("");

  // Patient Summary
  if (report.patient_summary) {
    lines.push("## Patient Summary");
    lines.push("");
    lines.push(report.patient_summary);
    lines.push("");
  }

  // Differential Diagnosis
  if (report.differential_diagnosis?.length) {
    lines.push("## Differential Diagnosis");
    lines.push("");
    for (const dx of report.differential_diagnosis) {
      lines.push(`### ${dx.diagnosis}`);
      lines.push("");
      lines.push(`- **Likelihood:** ${dx.likelihood}`);
      lines.push(`- **Reasoning:** ${dx.reasoning}`);
      if (dx.supporting_evidence?.length) {
        lines.push(`- **Supporting Evidence:** ${dx.supporting_evidence.join("; ")}`);
      }
      lines.push("");
    }
  }

  // Drug Interactions
  if (report.drug_interaction_warnings?.length) {
    lines.push("## Drug Interaction Warnings");
    lines.push("");
    for (const ix of report.drug_interaction_warnings) {
      lines.push(`- **${ix.drug_a} + ${ix.drug_b}** (${ix.severity}): ${ix.description}`);
    }
    lines.push("");
  }

  // Conflicts
  if (report.conflicts?.length) {
    lines.push("## Conflicts & Gaps Detected");
    lines.push("");
    for (const c of report.conflicts) {
      lines.push(`### ${c.conflict_type?.toUpperCase() || "CONFLICT"} - ${c.severity}`);
      lines.push("");
      lines.push(c.description);
      lines.push("");
      lines.push(`- **Guideline:** ${c.guideline_text} (${c.guideline_source})`);
      lines.push(`- **Patient Data:** ${c.patient_data}`);
      if (c.suggested_resolution) {
        lines.push(`- **Suggested Resolution:** ${c.suggested_resolution}`);
      }
      lines.push("");
    }
  }

  // Guideline Recommendations
  if (report.guideline_recommendations?.length) {
    lines.push("## Guideline-Concordant Recommendations");
    lines.push("");
    for (const rec of report.guideline_recommendations) {
      lines.push(`- ${rec}`);
    }
    lines.push("");
  }

  // Suggested Next Steps
  if (report.suggested_next_steps?.length) {
    lines.push("## Suggested Next Steps");
    lines.push("");
    for (const step of report.suggested_next_steps) {
      lines.push(`- **[${step.priority?.toUpperCase()}] ${step.action}** - ${step.rationale}`);
    }
    lines.push("");
  }

  // Caveats
  if (report.caveats?.length) {
    lines.push("## Caveats & Limitations");
    lines.push("");
    for (const caveat of report.caveats) {
      lines.push(`- ${caveat}`);
    }
    lines.push("");
  }

  // Sources
  if (report.sources_cited?.length) {
    lines.push("## Sources");
    lines.push("");
    report.sources_cited.forEach((source: string, i: number) => {
      lines.push(`${i + 1}. ${source}`);
    });
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push("*AI-generated clinical decision support - for demonstration purposes only. Does not replace professional medical judgment.*");
  lines.push("");

  return lines.join("\n");
}
