"use client";

interface Report {
  patient_summary: string;
  differential_diagnosis: Array<{
    diagnosis: string;
    likelihood: string;
    supporting_evidence: string[];
    reasoning: string;
  }>;
  drug_interaction_warnings: Array<{
    drug_a: string;
    drug_b: string;
    severity: string;
    description: string;
  }>;
  conflicts: Array<{
    conflict_type: string;
    severity: string;
    guideline_source: string;
    guideline_text: string;
    patient_data: string;
    description: string;
    suggested_resolution?: string;
  }>;
  guideline_recommendations: string[];
  suggested_next_steps: Array<{
    action: string;
    priority: string;
    rationale: string;
  }>;
  caveats: string[];
  sources_cited: string[];
}

interface CDSReportProps {
  report: Report;
}

const SEVERITY_BADGE: Record<string, string> = {
  critical: "bg-red-100 text-red-800 border-red-200",
  high: "bg-orange-100 text-orange-800 border-orange-200",
  moderate: "bg-yellow-100 text-yellow-800 border-yellow-200",
  low: "bg-green-100 text-green-800 border-green-200",
};

const LIKELIHOOD_BADGE: Record<string, string> = {
  high: "bg-red-100 text-red-700",
  moderate: "bg-yellow-100 text-yellow-700",
  low: "bg-gray-100 text-gray-600",
};

const CONFLICT_TYPE_LABEL: Record<string, string> = {
  omission: "Omission",
  contradiction: "Contradiction",
  dosage: "Dosage Concern",
  monitoring: "Monitoring Gap",
  allergy_risk: "Allergy Risk",
  interaction_gap: "Interaction Gap",
};

const CONFLICT_SEVERITY_STYLE: Record<string, { bg: string; border: string; icon: string }> = {
  critical: {
    bg: "bg-red-50",
    border: "border-red-400",
    icon: "🔴",
  },
  high: {
    bg: "bg-orange-50",
    border: "border-orange-400",
    icon: "🟠",
  },
  moderate: {
    bg: "bg-yellow-50",
    border: "border-yellow-400",
    icon: "🟡",
  },
  low: {
    bg: "bg-blue-50",
    border: "border-blue-300",
    icon: "🔵",
  },
};

export function CDSReport({ report }: CDSReportProps) {
  return (
    <div className="space-y-6">
      <div className="bg-white rounded-xl border border-gray-200 p-6">
        <h2 className="text-lg font-bold text-gray-900 mb-1">
          Clinical Decision Support Report
        </h2>
        <p className="text-xs text-gray-400">
          Generated by CDS Agent · MedGemma (HAI-DEF)
        </p>
      </div>

      {/* Patient Summary */}
      <Section title="📋 Patient Summary">
        <p className="text-sm text-gray-700 leading-relaxed">
          {report.patient_summary}
        </p>
      </Section>

      {/* Differential Diagnosis */}
      <Section title="🔍 Differential Diagnosis">
        <div className="space-y-3">
          {report.differential_diagnosis.map((dx, i) => (
            <div
              key={i}
              className="p-3 bg-gray-50 rounded-lg border border-gray-100"
            >
              <div className="flex items-center gap-2 mb-1">
                <span className="font-semibold text-sm text-gray-800">
                  {i + 1}. {dx.diagnosis}
                </span>
                <span
                  className={`text-xs px-2 py-0.5 rounded-full ${
                    LIKELIHOOD_BADGE[dx.likelihood] || LIKELIHOOD_BADGE.low
                  }`}
                >
                  {dx.likelihood} likelihood
                </span>
              </div>
              <p className="text-xs text-gray-600">{dx.reasoning}</p>
              {dx.supporting_evidence.length > 0 && (
                <div className="mt-2 flex flex-wrap gap-1">
                  {dx.supporting_evidence.map((ev, j) => (
                    <span
                      key={j}
                      className="text-xs bg-blue-50 text-blue-700 px-2 py-0.5 rounded"
                    >
                      {ev}
                    </span>
                  ))}
                </div>
              )}
            </div>
          ))}
        </div>
      </Section>

      {/* Drug Interactions */}
      {report.drug_interaction_warnings.length > 0 && (
        <Section title="⚠️ Drug Interaction Warnings">
          <div className="space-y-2">
            {report.drug_interaction_warnings.map((ix, i) => (
              <div
                key={i}
                className={`p-3 rounded-lg border ${
                  SEVERITY_BADGE[ix.severity] || SEVERITY_BADGE.moderate
                }`}
              >
                <div className="flex items-center gap-2 mb-1">
                  <span className="text-sm font-medium">
                    {ix.drug_a} + {ix.drug_b}
                  </span>
                  <span className="text-xs font-semibold uppercase">
                    {ix.severity}
                  </span>
                </div>
                <p className="text-xs">{ix.description}</p>
              </div>
            ))}
          </div>
        </Section>
      )}

      {/* Conflicts & Gaps — PROMINENTLY displayed */}
      {report.conflicts && report.conflicts.length > 0 && (
        <div className="bg-white rounded-xl border-2 border-red-300 p-5 ring-1 ring-red-100">
          <div className="flex items-center gap-2 mb-4">
            <span className="text-xl">🚨</span>
            <h3 className="text-base font-bold text-red-800">
              Conflicts &amp; Gaps Detected ({report.conflicts.length})
            </h3>
          </div>
          <p className="text-xs text-red-600 mb-4">
            The following conflicts were identified between clinical guideline
            recommendations and this patient&apos;s current data. Review each item
            carefully.
          </p>
          <div className="space-y-3">
            {report.conflicts.map((conflict, i) => {
              const style =
                CONFLICT_SEVERITY_STYLE[conflict.severity] ||
                CONFLICT_SEVERITY_STYLE.moderate;
              return (
                <div
                  key={i}
                  className={`p-4 rounded-lg border-l-4 ${style.bg} ${style.border}`}
                >
                  <div className="flex items-center gap-2 mb-2">
                    <span>{style.icon}</span>
                    <span className="text-xs font-bold uppercase text-gray-500">
                      {CONFLICT_TYPE_LABEL[conflict.conflict_type] ||
                        conflict.conflict_type}
                    </span>
                    <span className="text-xs font-semibold uppercase px-2 py-0.5 rounded bg-white/60">
                      {conflict.severity}
                    </span>
                  </div>
                  <p className="text-sm font-medium text-gray-800 mb-2">
                    {conflict.description}
                  </p>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs">
                    <div className="bg-white/50 rounded p-2">
                      <span className="font-semibold text-gray-500 block mb-0.5">
                        Guideline says:
                      </span>
                      <span className="text-gray-700">
                        {conflict.guideline_text}
                      </span>
                      <span className="block text-gray-400 mt-1">
                        — {conflict.guideline_source}
                      </span>
                    </div>
                    <div className="bg-white/50 rounded p-2">
                      <span className="font-semibold text-gray-500 block mb-0.5">
                        Patient data:
                      </span>
                      <span className="text-gray-700">
                        {conflict.patient_data}
                      </span>
                    </div>
                  </div>
                  {conflict.suggested_resolution && (
                    <div className="mt-2 p-2 bg-green-50 border border-green-200 rounded text-xs">
                      <span className="font-semibold text-green-700">
                        Suggested resolution:{" "}
                      </span>
                      <span className="text-green-800">
                        {conflict.suggested_resolution}
                      </span>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Guideline Recommendations */}
      {report.guideline_recommendations.length > 0 && (
        <Section title="📖 Guideline-Concordant Recommendations">
          <ul className="space-y-2">
            {report.guideline_recommendations.map((rec, i) => (
              <li key={i} className="flex items-start gap-2 text-sm text-gray-700">
                <span className="text-blue-500 mt-0.5">•</span>
                {rec}
              </li>
            ))}
          </ul>
        </Section>
      )}

      {/* Suggested Next Steps */}
      <Section title="➡️ Suggested Next Steps">
        <div className="space-y-2">
          {report.suggested_next_steps.map((step, i) => (
            <div key={i} className="flex items-start gap-3 p-2">
              <span
                className={`shrink-0 text-xs font-bold px-2 py-0.5 rounded border ${
                  SEVERITY_BADGE[step.priority] || SEVERITY_BADGE.moderate
                }`}
              >
                {step.priority.toUpperCase()}
              </span>
              <div>
                <p className="text-sm font-medium text-gray-800">
                  {step.action}
                </p>
                <p className="text-xs text-gray-500">{step.rationale}</p>
              </div>
            </div>
          ))}
        </div>
      </Section>

      {/* Caveats */}
      <Section title="⚡ Caveats & Limitations">
        <ul className="space-y-1">
          {report.caveats.map((caveat, i) => (
            <li key={i} className="text-xs text-amber-700 flex items-start gap-2">
              <span className="mt-0.5">⚠</span>
              {caveat}
            </li>
          ))}
        </ul>
      </Section>

      {/* Sources */}
      {report.sources_cited.length > 0 && (
        <Section title="📚 Sources">
          <ul className="space-y-1">
            {report.sources_cited.map((source, i) => (
              <li key={i} className="text-xs text-gray-500">
                [{i + 1}] {source}
              </li>
            ))}
          </ul>
        </Section>
      )}
    </div>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="bg-white rounded-xl border border-gray-200 p-5">
      <h3 className="text-sm font-semibold text-gray-700 mb-3">{title}</h3>
      {children}
    </div>
  );
}
