"use client";

interface Report {
  patient_summary: string;
  differential_diagnosis: Array<{
    diagnosis: string;
    likelihood: string;
    supporting_evidence: string[];
    reasoning: string;
  }>;
  drug_interaction_warnings: Array<{
    drug_a: string;
    drug_b: string;
    severity: string;
    description: string;
  }>;
  guideline_recommendations: string[];
  suggested_next_steps: Array<{
    action: string;
    priority: string;
    rationale: string;
  }>;
  caveats: string[];
  sources_cited: string[];
}

interface CDSReportProps {
  report: Report;
}

const SEVERITY_BADGE: Record<string, string> = {
  critical: "bg-red-100 text-red-800 border-red-200",
  high: "bg-orange-100 text-orange-800 border-orange-200",
  moderate: "bg-yellow-100 text-yellow-800 border-yellow-200",
  low: "bg-green-100 text-green-800 border-green-200",
};

const LIKELIHOOD_BADGE: Record<string, string> = {
  high: "bg-red-100 text-red-700",
  moderate: "bg-yellow-100 text-yellow-700",
  low: "bg-gray-100 text-gray-600",
};

export function CDSReport({ report }: CDSReportProps) {
  return (
    <div className="space-y-6">
      <div className="bg-white rounded-xl border border-gray-200 p-6">
        <h2 className="text-lg font-bold text-gray-900 mb-1">
          Clinical Decision Support Report
        </h2>
        <p className="text-xs text-gray-400">
          Generated by CDS Agent · MedGemma (HAI-DEF)
        </p>
      </div>

      {/* Patient Summary */}
      <Section title="📋 Patient Summary">
        <p className="text-sm text-gray-700 leading-relaxed">
          {report.patient_summary}
        </p>
      </Section>

      {/* Differential Diagnosis */}
      <Section title="🔍 Differential Diagnosis">
        <div className="space-y-3">
          {report.differential_diagnosis.map((dx, i) => (
            <div
              key={i}
              className="p-3 bg-gray-50 rounded-lg border border-gray-100"
            >
              <div className="flex items-center gap-2 mb-1">
                <span className="font-semibold text-sm text-gray-800">
                  {i + 1}. {dx.diagnosis}
                </span>
                <span
                  className={`text-xs px-2 py-0.5 rounded-full ${
                    LIKELIHOOD_BADGE[dx.likelihood] || LIKELIHOOD_BADGE.low
                  }`}
                >
                  {dx.likelihood} likelihood
                </span>
              </div>
              <p className="text-xs text-gray-600">{dx.reasoning}</p>
              {dx.supporting_evidence.length > 0 && (
                <div className="mt-2 flex flex-wrap gap-1">
                  {dx.supporting_evidence.map((ev, j) => (
                    <span
                      key={j}
                      className="text-xs bg-blue-50 text-blue-700 px-2 py-0.5 rounded"
                    >
                      {ev}
                    </span>
                  ))}
                </div>
              )}
            </div>
          ))}
        </div>
      </Section>

      {/* Drug Interactions */}
      {report.drug_interaction_warnings.length > 0 && (
        <Section title="⚠️ Drug Interaction Warnings">
          <div className="space-y-2">
            {report.drug_interaction_warnings.map((ix, i) => (
              <div
                key={i}
                className={`p-3 rounded-lg border ${
                  SEVERITY_BADGE[ix.severity] || SEVERITY_BADGE.moderate
                }`}
              >
                <div className="flex items-center gap-2 mb-1">
                  <span className="text-sm font-medium">
                    {ix.drug_a} + {ix.drug_b}
                  </span>
                  <span className="text-xs font-semibold uppercase">
                    {ix.severity}
                  </span>
                </div>
                <p className="text-xs">{ix.description}</p>
              </div>
            ))}
          </div>
        </Section>
      )}

      {/* Guideline Recommendations */}
      {report.guideline_recommendations.length > 0 && (
        <Section title="📖 Guideline-Concordant Recommendations">
          <ul className="space-y-2">
            {report.guideline_recommendations.map((rec, i) => (
              <li key={i} className="flex items-start gap-2 text-sm text-gray-700">
                <span className="text-blue-500 mt-0.5">•</span>
                {rec}
              </li>
            ))}
          </ul>
        </Section>
      )}

      {/* Suggested Next Steps */}
      <Section title="➡️ Suggested Next Steps">
        <div className="space-y-2">
          {report.suggested_next_steps.map((step, i) => (
            <div key={i} className="flex items-start gap-3 p-2">
              <span
                className={`shrink-0 text-xs font-bold px-2 py-0.5 rounded border ${
                  SEVERITY_BADGE[step.priority] || SEVERITY_BADGE.moderate
                }`}
              >
                {step.priority.toUpperCase()}
              </span>
              <div>
                <p className="text-sm font-medium text-gray-800">
                  {step.action}
                </p>
                <p className="text-xs text-gray-500">{step.rationale}</p>
              </div>
            </div>
          ))}
        </div>
      </Section>

      {/* Caveats */}
      <Section title="⚡ Caveats & Limitations">
        <ul className="space-y-1">
          {report.caveats.map((caveat, i) => (
            <li key={i} className="text-xs text-amber-700 flex items-start gap-2">
              <span className="mt-0.5">⚠</span>
              {caveat}
            </li>
          ))}
        </ul>
      </Section>

      {/* Sources */}
      {report.sources_cited.length > 0 && (
        <Section title="📚 Sources">
          <ul className="space-y-1">
            {report.sources_cited.map((source, i) => (
              <li key={i} className="text-xs text-gray-500">
                [{i + 1}] {source}
              </li>
            ))}
          </ul>
        </Section>
      )}
    </div>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="bg-white rounded-xl border border-gray-200 p-5">
      <h3 className="text-sm font-semibold text-gray-700 mb-3">{title}</h3>
      {children}
    </div>
  );
}
